### ISSUE TITLE
Better appstream summary

### ISSUE THREAD

**Issue by bertob** [nokyan/resources#149]
The current summary "Monitor your system resources and processes" is too long (35 characters max). How about something like "Monitor system resources" or "Keep an eye on system resources"?

See the guidelines for more detail: https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines

**Comment by nokyan** [comment]
Hi, thanks for the issue. :)
I've been thinking about this as well since the recent guideline changes, though I haven't yet come up with something that I like. I'd like to keep "processes" in there somewhere but I reckon that's not quite possible.
I like your idea "Keep an eye on system resources" though, it sounds friendlier and less technical. I think I might just go with that. :)
