### ISSUE TITLE
clearer presentation of device batteries

### ISSUE THREAD

**Issue by TheRsKing** [nokyan/resources#259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

for example, i have a wireless logitech mouse, when i connect it via cable, its battery statistics are also displayed in resources. but this is hardly distinguishable from device batteries and can therefore cause confusion

### Describe the solution you'd like

it would be useful to use a different color for external devices and to mention the device name in the sidebar

### Additional context

![grafik](https://github.com/nokyan/resources/assets/130909958/af5bc23e-f8c5-433c-b72f-20d9b2074ef9)

**Comment by nokyan** [comment]
Hi, thanks for the issue.
I'll look into how to distinguish laptop batteries from e.g. mouse batteries. Hopefully the device name (in your case "hidpp[…]" is consistent and conclusive enough.

**Comment by TheRsKing** [comment]
hey thanks!
what about using the model name for external devices?

**Comment by nokyan** [comment]
> hey thanks! what about using the model name for external devices?

I would've gone for that too but the problem is that the model name isn't always useful. For example, the model name of my notebook is apparently "0x4C 0x32 0x31 0x4D 0x34 0x50 0x45 0x32". I didn't reencode this or anything, this is exactly what comes out of the "model_name" file in SysFS and I've seen other instances of other weird encodings online. This example does decode to proper UTF-8 though, maybe I'll implement some decoding mechanisms for Resources to try.
