### ISSUE TITLE
Sidebar theming issue with libadwaita + Gradience

### ISSUE THREAD

**Issue by stankovictab** [nokyan/resources#264]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

I'm using Gradience to change the look of libadwaita apps on my system. 
On Resources, the left sidebar when the app is maximized isn't being themed like the rest of the app. 
Works fine when in a smaller window. 
It's not an issue with the theme selected in Gradience as far as I can see. 
![2024-06-27_08-27-06](https://github.com/nokyan/resources/assets/62820268/2d4fcd85-938f-40bf-8fb8-df3555990782)
![2024-06-27_08-27-16](https://github.com/nokyan/resources/assets/62820268/2fefadbc-acc7-42f6-a1c8-41ff0010ef90)

### Expected Behavior

The sidebar is themed

### Steps To Reproduce

1. Install Gradience
2. Set a theme (in this case it's Catppuccin)
3. Launch Resources

### Environment

```markdown
Flatpak 1.4.0, Nobara (Fedora) 39
```

**Comment by stankovictab** [comment]
Happens on 1.5.0 too.

**Comment by nokyan** [comment]
Hi,
in my testing, this issue exists also for Files and Settings, though I cannot exactly reproduce it for Resources since Gradience doesn't seem to work for Flatpaks for me.
![Screenshot from 2024-06-27 20-49-27](https://github.com/nokyan/resources/assets/20604611/4d006706-6498-48f9-b847-415976695bff)
![Screenshot from 2024-06-27 20-49-24](https://github.com/nokyan/resources/assets/20604611/d7b2cc22-19c7-4a68-8f1d-28540f09b1bf)
I think this might be an issue with either libadwaita or Gradience.

**Comment by stankovictab** [comment]
I'm using KDE so I didn't notice it on Gnome Files 😅 
It must be - I'll close this issue then.

**Comment by stankovictab** [comment]
This does appear to be a Gradience issue. https://github.com/GradienceTeam/Gradience/issues/899
There is a temporary fix using custom CSS. 
```css
@define-color sidebar_bg_color @card_bg_color;
@define-color sidebar_fg_color @card_fg_color;
@define-color sidebar_shade_color @shade_color;
@define-color sidebar_border_color @headerbar_border_color;
@define-color sidebar_backdrop_color @headerbar_backdrop_color;
```
