### ISSUE TITLE
2 TB SSD progress bar goes up and down continuously

### ISSUE THREAD

**Issue by ThinkerDreamer** [nokyan/resources#39]
Hello! I don't know if this is the expected behavior, but it seems kind of confusing to me.
On the left sidebar, the progress bar for my SSD which has `/`, `/home`, and my swap partition mounted continuously fills and unfills in a similar way to the memory and processor progress bars. Those two are understandable, but even when I click on the tab for my SSD, it says "Total usage:" and bounces between 0% and up to 34%, which doesn't seem quite right. 

I'm on Mint 21.2 and this SSD is a Samsung 980 Pro 2 TB.

https://github.com/nokyan/resources/assets/74881094/6f27439c-26a7-433c-aa54-43855575bcf3

"Total usage" I would expect to mean used space, not transfer bandwidth, if that's what it is.

**Comment by nokyan** [comment]
Hi! Total Usage in this case doesn't refer to bandwidth per se, but to how much time the drive has spent writing or reading data since the last time the view was updated. And since the 2 TB drive is your system drive, it's probably reading and writing small bits of data all the time. Though I agree, the term "Total Usage" in this context may be a bit misleading.

**Comment by nokyan** [comment]
Resolved as of ddacda0, "Total Usage" has been replaced with "Drive Activity".
