### ISSUE TITLE
Some native apps not listed under 'Applications'

### ISSUE THREAD

**Issue by Jack-Balcombe** [nokyan/resources#41]
Hi,
I am using Resources on Linux Mint 21.2, and some of my apps are not displayed in the 'applications' tab when they are open. The processes for these apps still show up in the processes tab, but they are not recognised as apps.

The apps that don't show up are all installed natively (Flatpaks seem to work fine), and include LibreOffice and ClamTK. Resources seems to be able to detect other native apps, such as Firefox and Atril, without any issues.

Resources displaying Atril on the applications list, but not LibreOffice or ClamTK (I scrolled further down as well but they were not there either):
![ksnip_20231017-051721](https://github.com/nokyan/resources/assets/100166813/7e2109d1-adad-4fa9-af68-c3c7c0eb399a)

**Comment by nokyan** [comment]
Hi, thanks for raising the issue.
Resources has an algorithm to decide which process belongs to which app, in special cases that may fail. I'll look into this. :)

**Comment by sokorototo** [comment]
One other example is vscode, when installed natively. A good algorithm is to assume applications are processes that have opened a window. Also, you could add high CPU usage processes to a separate `Intensive Processes` list under processes.

**Comment by nokyan** [comment]
> Also, you could add high CPU usage processes to a separate `Intensive Processes` list under processes.
You can just sort after CPU usage, this doesn't really warrant a new view in my opinion.

**Comment by Jack-Balcombe** [comment]
> One other example is vscode, when installed natively. A good algorithm is to assume applications are processes that have opened a window. Also, you could add high CPU usage processes to a separate `Intensive Processes` list under processes. Some processes also don't open windows, but open new children that open windows, vscode for example. So it might be useful to traverse the process tree

Is it intended behaviour for Resources to display things like Network, Cinnamon, Evolution Alarm Notify etc. as apps? If not, this approach could resolve that problem too

**Comment by sokorototo** [comment]
If you don't mind, what algorithm do you use to determine whether a process is an Application? I launched a game on Steam and it then determined the whole steam process tree to be an application under the game?

**Comment by nokyan** [comment]
> If you don't mind, what algorithm do you use to determine whether a process is an Application? I launched a game on Steam and it then determined the whole Steam process tree to be an application under the game. Ideally, would the game _and_ steam be separate applications?

First, Resources gathers all installed applications by looking for .desktop files in known folders such as /usr/share/applications. It also gathers the commandline of the applications and the ID of the applications either by an X-Flatpak entry in the file itself or if that's not available, it'll just take the name of the .desktop file.
For finding out, which application a process belongs to, Resources tries to:

1. find an applications ID in the control group of the process (such as org.mozilla.firefox in case of the Firefox flatpak)
2. find an applications ID in the path of the process' executable (such as /usr/bin/firefox)
3. find an applications ID in the name of the process' executable (such as firefox)
4. find the process' executable path in an application's commandline
5. find the process' executable name in an application's commandline
6. look up the process' executable name in a look-up table for known exceptions (Firefox for example apparently uses a binary called firefox-bin for its tabs, which would not be recognized as belonging to the Firefox app using any of the above methods since firefox-bin is never mentioned in the .desktop file)

If none of that works, the process is considered a system process.
For Steam games, the issue is that the game's process control group is set to steam, and since that's the first thing Resources looks for, it's considered to be a part of Steam.

**Comment by sokorototo** [comment]
One small issue with parsing `.dessktop` files. It kind of falls apart when the .desktop file launches a "provider" application like Steam or Lutris. This results in Resources thinking the Steam tree of processes is a specific game, instead of recognizing the game and Steam as separate applications.

**Comment by nokyan** [comment]
> One small issue with parsing `.dessktop` files. It kind of falls apart when the .desktop file launches a "provider" application like Steam or Lutris. This results in Resources thinking the Steam tree of processes is a specific game, instead of recognizing the game and Steam as separate applications.

Maybe I'll find something to be able to distinguish between Steam and Steam games, I wouldn't hold my breath though. :/

**Comment by sokorototo** [comment]
How does Windows do it? Dave's Garage has a video on how the task manager works on Windows. It's of an old version but some hints could be taken. https://youtu.be/Ve95Nh690l0?si=a9PaWKPTgUYruJRQ

**Comment by Jack-Balcombe** [comment]
I've noticed that Resources can now detect LibreOffice being open on my computer. However, LibreOffice always shows up in the apps list as LibreOffice Draw, even if a different program in the office suite (eg. Writer, Calc) is open and Draw isn't open.

ClamTK still does not show up on the apps list.

**Comment by Jack-Balcombe** [comment]
An issue opened on the Cinnamon Github by the Mission Center devs that may be relevant:
https://github.com/linuxmint/cinnamon/issues/12015

I am not sure if Resources determines which processes are applications in a similar way to how Mission Center does it. But if it does, this could be relevant
